<?php

namespace Database\Seeders;

use App\Models\Restaurant;
use App\Models\User;
use Illuminate\Database\Seeder;

class RestaurantSeeder extends Seeder
{
    public function run(): void
    {
        $owner = User::where('role', 'owner')->first() ?: User::factory()->create(['role' => 'owner', 'name' => 'John Owner', 'email' => 'owner@example.com']);

        // Sample image URLs (using unsplash for demo)
        $sampleImages = [
            'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400',
            'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=400',
            'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=400',
            'https://images.unsplash.com/photo-1544148103-0773bf10d330?w=400',
            'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=400',
            'https://images.unsplash.com/photo-1579027989536-b7b1f875659b?w=400',
            'https://images.unsplash.com/photo-1550966871-3ed3cdb51f3a?w=400',
            'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400',
            'https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=400',
            'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400',
            'https://images.unsplash.com/photo-1506354666786-959d6d497f1a?w=400',
            'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=400',
            'https://images.unsplash.com/photo-1517244683847-7456b63c5969?w=400',
            'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400',
            'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400',
        ];

        $restaurants = [
            // Casablanca (3 restaurants)
            [
                'name' => 'La Mammia Pizza',
                'description' => 'Authentic Italian pizzas baked in a wood-fired oven.',
                'address' => '123 Rue de Rome, Casablanca',
                'latitude' => 33.5731,
                'longitude' => -7.5898,
                'cuisine_type' => 'Pizza',
                'price_range' => '$$',
                'rating' => 4.5,
                'phone' => '+212 522-123456',
                'opening_time' => '12:00:00',
                'closing_time' => '23:00:00',
                'image_url' => $sampleImages[0],
            ],
            [
                'name' => 'Le Gourmet Marocain',
                'description' => 'Discover the best of Moroccan traditional cuisine.',
                'address' => '45 Boulevard d\'Anfa, Casablanca',
                'latitude' => 33.5883,
                'longitude' => -7.6326,
                'cuisine_type' => 'Marocain',
                'price_range' => '$$$',
                'rating' => 4.8,
                'phone' => '+212 522-654321',
                'opening_time' => '11:00:00',
                'closing_time' => '22:30:00',
                'image_url' => $sampleImages[1],
            ],
            [
                'name' => 'Sushi Zen',
                'description' => 'Fresh sushi and sashimi in a minimalist atmosphere.',
                'address' => '78 Avenue des FAR, Casablanca',
                'latitude' => 33.5950,
                'longitude' => -7.6186,
                'cuisine_type' => 'Sushi',
                'price_range' => '$$$',
                'rating' => 4.2,
                'phone' => '+212 522-987654',
                'opening_time' => '12:30:00',
                'closing_time' => '22:00:00',
                'image_url' => $sampleImages[2],
            ],
            // Tanger (3 restaurants)
            [
                'name' => 'Le Palais du Burger',
                'description' => 'Gourmet burgers with a Moroccan twist.',
                'address' => '25 Avenue Mohammed VI, Tanger',
                'latitude' => 35.7595,
                'longitude' => -5.8340,
                'cuisine_type' => 'Burger',
                'price_range' => '$$',
                'rating' => 4.3,
                'phone' => '+212 539-123456',
                'opening_time' => '11:00:00',
                'closing_time' => '23:00:00',
                'image_url' => $sampleImages[3],
            ],
            [
                'name' => 'Dar Warda',
                'description' => 'Traditional Moroccan dishes in a historic setting.',
                'address' => '88 Rue de la Liberté, Tanger',
                'latitude' => 35.7569,
                'longitude' => -5.8010,
                'cuisine_type' => 'Marocain',
                'price_range' => '$$$',
                'rating' => 4.7,
                'phone' => '+212 539-234567',
                'opening_time' => '12:00:00',
                'closing_time' => '22:00:00',
                'image_url' => $sampleImages[4],
            ],
            [
                'name' => 'Pizzeria Napoli',
                'description' => 'Authentic Italian pizzas and pastas.',
                'address' => '12 Boulevard Pasteur, Tanger',
                'latitude' => 35.7610,
                'longitude' => -5.7990,
                'cuisine_type' => 'Pizza',
                'price_range' => '$$',
                'rating' => 4.4,
                'phone' => '+212 539-345678',
                'opening_time' => '12:00:00',
                'closing_time' => '23:00:00',
                'image_url' => $sampleImages[5],
            ],
            // Rabat (3 restaurants)
            [
                'name' => 'Le Jardin Secret',
                'description' => 'Elegant French-Moroccan fusion in a garden setting.',
                'address' => '42 Rue Oued El Makhazine, Rabat',
                'latitude' => 34.0209,
                'longitude' => -6.8416,
                'cuisine_type' => 'Fusion',
                'price_range' => '$$$',
                'rating' => 4.8,
                'phone' => '+212 537-123456',
                'opening_time' => '12:00:00',
                'closing_time' => '23:00:00',
                'image_url' => $sampleImages[6],
            ],
            [
                'name' => 'Dar Naim',
                'description' => 'Traditional Rabat cuisine with modern presentation.',
                'address' => '18 Rue Abou Inlia, Rabat',
                'latitude' => 34.0250,
                'longitude' => -6.8350,
                'cuisine_type' => 'Marocain',
                'price_range' => '$$$',
                'rating' => 4.6,
                'phone' => '+212 537-234567',
                'opening_time' => '11:30:00',
                'closing_time' => '22:00:00',
                'image_url' => $sampleImages[7],
            ],
            [
                'name' => 'Pizza Roma',
                'description' => 'Wood-fired pizzas and Italian specialties.',
                'address' => '73 Avenue Ibn Khaldoun, Rabat',
                'latitude' => 34.0180,
                'longitude' => -6.8450,
                'cuisine_type' => 'Pizza',
                'price_range' => '$$',
                'rating' => 4.3,
                'phone' => '+212 537-345678',
                'opening_time' => '12:00:00',
                'closing_time' => '23:00:00',
                'image_url' => $sampleImages[8],
            ],
            // Larache (3 restaurants)
            [
                'name' => 'Riad Larache',
                'description' => 'Traditional Moroccan hospitality and cuisine.',
                'address' => '15 Rue Ibn Khaldoun, Larache',
                'latitude' => 35.1982,
                'longitude' => -6.1546,
                'cuisine_type' => 'Marocain',
                'price_range' => '$$',
                'rating' => 4.5,
                'phone' => '+212 539-111111',
                'opening_time' => '12:00:00',
                'closing_time' => '22:00:00',
                'image_url' => $sampleImages[9],
            ],
            [
                'name' => 'El Ksar',
                'description' => 'Authentic Moroccan tagines and couscous.',
                'address' => '28 Avenue Hassan II, Larache',
                'latitude' => 35.1950,
                'longitude' => -6.1500,
                'cuisine_type' => 'Marocain',
                'price_range' => '$$',
                'rating' => 4.2,
                'phone' => '+212 539-222222',
                'opening_time' => '11:00:00',
                'closing_time' => '21:30:00',
                'image_url' => $sampleImages[10],
            ],
            [
                'name' => 'La Marine',
                'description' => 'Fresh seafood right by the port.',
                'address' => 'Quai de pêche, Larache',
                'latitude' => 35.2020,
                'longitude' => -6.1600,
                'cuisine_type' => 'Poisson',
                'price_range' => '$$$',
                'rating' => 4.4,
                'phone' => '+212 539-333333',
                'opening_time' => '11:00:00',
                'closing_time' => '22:00:00',
                'image_url' => $sampleImages[11],
            ],
            // Tetouan (3 restaurants)
            [
                'name' => 'Dar Naila',
                'description' => 'Traditional Tetouan cuisine in a riad setting.',
                'address' => '25 Rue Nala, Tetouan',
                'latitude' => 35.5780,
                'longitude' => -5.3680,
                'cuisine_type' => 'Marocain',
                'price_range' => '$$',
                'rating' => 4.7,
                'phone' => '+212 539-444444',
                'opening_time' => '12:00:00',
                'closing_time' => '22:30:00',
                'image_url' => $sampleImages[12],
            ],
            [
                'name' => 'Pizzeria Al Andalus',
                'description' => 'Italian cuisine with a view of the Rif mountains.',
                'address' => '88 Avenue Mohammed V, Tetouan',
                'latitude' => 35.5700,
                'longitude' => -5.3600,
                'cuisine_type' => 'Pizza',
                'price_range' => '$$',
                'rating' => 4.3,
                'phone' => '+212 539-555555',
                'opening_time' => '12:00:00',
                'closing_time' => '23:00:00',
                'image_url' => $sampleImages[13],
            ],
            [
                'name' => 'Sahara Palace',
                'description' => 'Exquisite Moroccan and international dishes.',
                'address' => '42 Rue du Sahara, Tetouan',
                'latitude' => 35.5750,
                'longitude' => -5.3650,
                'cuisine_type' => 'Fusion',
                'price_range' => '$$$',
                'rating' => 4.6,
                'phone' => '+212 539-666666',
                'opening_time' => '11:00:00',
                'closing_time' => '22:00:00',
                'image_url' => $sampleImages[14],
            ],
        ];

        foreach ($restaurants as $data) {
            $data['user_id'] = $owner->id;
            Restaurant::create($data);
        }
    }
}
